Repository ripe-tech/ripe-commons-vue, pull requests merged in 2021-02, with the labels that each got.

#1 fix: compilation
  .stylelintrc.js
  index.js
  package.json
  vue/index.js
Labels: bug

#2 Add missing .github folder
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/user_story.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy.yml
  .github/workflows/main.yml
Labels: enhancement

#3 Remove storybook
  .eslintignore
  .gitignore
  .prettierignore
  package.json
Labels: enhancement

#4 Setup Vue tests
  package.json
  vue/test/base.js
  vue/test/setup.js
  vue/test/webpack.config.js
Labels: bug

#6 Add timeSince
  vue/mixins/utils.js
Labels: back-port 🔮, enhancement

#5 #44 localeMixin
  vue/mixins/index.js
  vue/mixins/locales.js
  vue/test/mixins/locales/locales.test.js
Labels: documentation, enhancement, unit-testing
